name: Build and Publish Precompiled Binaries

on:
  push:
    tags:
      - 'v*' # Trigger workflow on version tags (e.g., v1.0.0)
    branches:
      - 'use-precompiled-binaries-with-node-api' # Trigger workflow on pull requests to any branch

jobs:
  build-and-publish:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16, 18, 19, 20, 21, 22, 23] # Node.js versions to build for
        platform: [win32] # Platforms to target
        architecture: [x64, arm64] # Architectures to support

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 4: Cache Node.js `node-gyp` builds
      - name: Cache node-gyp build artifacts
        uses: actions/cache@v3
        with:
          path: ~/.cache/node-gyp
          key: ${{ runner.os }}-node-gyp-${{ matrix.node-version }}-${{ matrix.architecture }}
          restore-keys: |
            ${{ runner.os }}-node-gyp-${{ matrix.node-version }}-

      # Step 5: Install dependencies
      - name: Install dependencies
        run: npm run installFromSource

      # Step 6: Build binary
      - name: Build binary for ${{ matrix.platform }} ${{ matrix.architecture }}
        run: npm run prebuild
        env:
          npm_config_arch: ${{ matrix.architecture }}
          npm_config_platform: ${{ matrix.platform }}

      # Step 7: Test the binary
      - name: Test the binary
        run: npm run testbinary
        env:
          npm_config_arch: ${{ matrix.architecture }}
          npm_config_platform: ${{ matrix.platform }}
          
      # Step 7.5: Create binding.gyp location file
      - name: Create binding location file
        run: node createBindingLocation.js

      # Step 8: Commit binary to the repository
      - name: Commit binary to the repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Add built binaries for ${{ matrix.platform }} ${{ matrix.architecture }} with Node.js ${{ matrix.node-version }}"
          git push
          git push
