name: Node.js Package

on:
  release:
    types: [created]

jobs:
  create-node-binds:
    uses: ./.github/workflows/create-node-binds.yml
  build:
    needs: create-node-binds
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: installFromSource # will run `yarn install` command

  publish-gpr:
    needs: build
    runs-on: windows-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
